/**
 * Supported languages for the static UI (labels, buttons, headings, card
 * chrome). Farmer-facing ADVICE TEXT generated by the backend (module
 * summaries, farmer_actions, warnings, reasons) is NOT translated by this
 * system yet - it stays English regardless of the selected language. This
 * is a deliberate, documented scope boundary (see README > Multilingual UI),
 * not an oversight: translating ~50+ backend f-string templates across 9
 * modules is a separate, much larger effort.
 *
 * Translations were written directly (not machine-translated via an API,
 * not reviewed by a native speaker of each language) - the 4 form-critical
 * languages this app already used (English, Hindi) are the ones we can
 * vouch for most confidently; the rest cover common, standard agricultural/
 * UI vocabulary but should be reviewed by a native speaker before real
 * farmer deployment. Flagged in README, not hidden.
 */

export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
] as const;

export type LanguageCode = (typeof SUPPORTED_LANGUAGES)[number]["code"];

export const DEFAULT_LANGUAGE: LanguageCode = "en";

export const LANGUAGE_STORAGE_KEY = "kisan-mitra-lang";

export function isSupportedLanguage(value: string | null): value is LanguageCode {
  return !!value && SUPPORTED_LANGUAGES.some((l) => l.code === value);
}
